name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      
      with:
        python-version: '3.8'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yaml
        activate-environment: work-at-gojek

    - name: Install Node.js
      run: conda install -c conda-forge nodejs

    - name: Install CML
      run: npm install -g @dvcorg/cml

    - name: Run the pipeline (Makefile)
      run: make run

    - name: Post metrics to GitHub as a comment
      run: cml comment create report.md
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
