name: CI Pipeline
on:
  push:
    branches:[ "main" ]
    pull_request:
      branches:["main"]
    workflow_dispatch:

jobs:
  build:
    runs_on: ubuntu-latest
    # container:
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
  
